### ISSUE TITLE
Real IllegalArgumentException exception was thrown executing .array-data

### ISSUE THREAD

**Issue by LeAndroid21** [CalebFenton/simplify#104]
i use command line to input:
```
java -jar simplify-1.2.0.jar -it 'com/tencent/mm' -o d:/output/apk com.tencent.mm_5.3.1.49.apk
```
there is result:
```
(2 / 2) Executing top level method: Lcom/tencent/mm/protocal/a/vx;-><init>()V
Simplifying: Lcom/tencent/mm/protocal/a/vx;-><init>()V
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 0
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
[6 / 7435] Processing top level class Lcom/tencent/mm/ui/contact/profile/by;
(1 / 3) Executing top level method: Lcom/tencent/mm/ui/contact/profile/by;->getHint()Ljava/lang/CharSequence;
Simplifying: Lcom/tencent/mm/ui/contact/profile/by;->getHint()Ljava/lang/CharSequence;
Optimizations:
        constantized ifs = 0
        constantized ops = 1
        dead assignments removed = 0
        dead ops removed = 0
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
(2 / 3) Executing top level method: Lcom/tencent/mm/ui/contact/profile/by;->a(Lcom/tencent/mm/ui/contact/profile/HelperHeaderPreference;)V
14:42:37.236 WARN  NodeExecutor - ExecutionNode{signature=Lcom/tencent/mm/model/bg;->qk()Lcom/tencent/mm/model/b;, op=invoke-static {}, Lcom/tencent/mm/sdk/platformtools/cf;->aFN()Lcom/tencent/mm/sdk/platformtools/cj;, @=64} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception:
java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/tencent/mm/sdk/platformtools/cf;-><clinit>()V, op=.array-data 8
        300
        200
        300
        200
.end array-data, @=60} and was not handled. This could be a bug in smalivm.
Exception: java.lang.IllegalArgumentException
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:91)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:205)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:96)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
        at org.cf.simplify.Launcher.run(Launcher.java:141)
        at org.cf.simplify.Main.main(Main.java:14)
14:42:37.240 WARN  NodeExecutor - ExecutionNode{signature=Lcom/tencent/mm/model/bg;->qk()Lcom/tencent/mm/model/b;, op=invoke-static {}, Lcom/tencent/mm/sdk/platformtools/cf;->aFN()Lcom/tencent/mm/sdk/platformtools/cj;, @=64} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception:
java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/tencent/mm/sdk/platformtools/cf;-><clinit>()V, op=.array-data 8
        300
        200
        300
        200
.end array-data, @=60} and was not handled. This could be a bug in smalivm.
Exception: java.lang.IllegalArgumentException
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:91)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:205)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:96)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:353)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:128)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:80)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
        at org.cf.simplify.Launcher.run(Launcher.java:141)
        at org.cf.simplify.Main.main(Main.java:14)
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/tencent/mm/ui/contact/profile/by;->a(Lcom/tencent/mm/ui/contact/profile/HelperHeaderPreference;)V, op=invoke-static {}, Lcom/tencent/mm/model/x;->pc()I, @=0} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/tencent/mm/model/x;->pc()I, op=invoke-static {}, Lcom/tencent/mm/model/bg;->qk()Lcom/tencent/mm/model/b;, @=0} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/tencent/mm/model/bg;->qk()Lcom/tencent/mm/model/b;, op=throw r0, @=158} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:91)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:61)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
        at org.cf.simplify.Launcher.run(Launcher.java:141)
        at org.cf.simplify.Main.main(Main.java:14)
```

[com.tencent.mm_5.3.1.49.zip](https://github.com/CalebFenton/simplify/files/2136021/com.tencent.mm_5.3.1.49.zip)
help me ,there is why?

**Comment by CalebFenton** [comment]
This looks _really_ weird because it's bombing out at an `array-data` op, which probably shouldn't even be getting executed. Looks like you've given me enough to reproduce, so I'll look into it.

**Comment by LeAndroid21** [comment]
Thanks Caleb, I am looking forward to your results
