### ISSUE TITLE
Null pointer from InvokeOpCodeFactor -- unknown cause

### ISSUE THREAD

**Issue by strazzere** [CalebFenton/simplify#111]
Was trying to assist someone and was curious if simplify would work - it ended up throwing a null pointer which I don't have time to investigate. However I simplified (oh boy) the code into a test case into a minimal reproducable case;

```
.class public Lrednaga/reproduce/testcase/uno;
.super Ljava/lang/Object;

# direct methods
.method public constructor <init>()V
    .registers 1

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods

.method public toString()Ljava/lang/String;
    .registers 3

    new-instance v0, Ljava/lang/StringBuffer;
    invoke-direct {v0}, Ljava/lang/StringBuffer;-><init>()V

    const-string v1, "L"
    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->reallocate(Ljava/lang/String;)Ljava/lang/StringBuffer;
    move-result-object v0

    invoke-static {p0}, Ljava/lang/System;->identityHashCode(Ljava/lang/Object;)I
    move-result v1

    invoke-virtual {v0, v1}, Ljava/lang/StringBuffer;->reallocate(I)Ljava/lang/StringBuffer;
    move-result-object v0

    invoke-virtual {v0}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;
    move-result-object v0

    return-object v0
.end method
```

It's pretty meaningless code, doesn't do anything and I'm not thinking it's anti-analysis. However it does cause a crash;

```
diff@milo:~/repo/simplify$ java -jar simplify/build/libs/simplify-1.2.0.jar tests/
[1 / 1] Processing top level class Lrednaga/reproduce/testcase/uno;
(1 / 2) Executing top level method: Lrednaga/reproduce/testcase/uno;->toString()Ljava/lang/String;
Exception in thread "main" java.lang.NullPointerException
	at org.cf.smalivm.opcode.InvokeOpFactory.create(InvokeOpFactory.java:87)
	at org.cf.smalivm.opcode.OpCreator.create(OpCreator.java:29)
	at org.cf.smalivm.context.ExecutionGraph.buildLocationToNodePile(ExecutionGraph.java:105)
	at org.cf.smalivm.context.ExecutionGraph.<init>(ExecutionGraph.java:78)
	at org.cf.smalivm.VirtualMachine.updateInstructionGraph(VirtualMachine.java:188)
	at org.cf.smalivm.VirtualMachine.spawnInstructionGraph(VirtualMachine.java:139)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:98)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
	at org.cf.simplify.Launcher.run(Launcher.java:141)
	at org.cf.simplify.Main.main(Main.java:14)
```

Someone is more than welcome to take this up - otherwise I'll look into it when I have a chance.

**Comment by CalebFenton** [comment]
It looks like `reallocate` doesn't exist. I can't find any reference to `Ljava/lang/StringBuffer;->reallocate(I)Ljava/lang/StringBuffer;` in documentation or in the framework code. How did you find this?

This is a really ugly error message, at least. So I'll look into making that better. Closing this for now, feel free to re-open.
