### ISSUE TITLE
Virtual UnsupportedOperationException thrown when executing com.google.android.games internal class

### ISSUE THREAD

**Issue by AndnixSH** [CalebFenton/simplify#112]
Simplify fails to deobfuscate obfuscated dex by dxsheld.

APK file: https://usersdownload.com/bl3pz6b8qmbp.html

```
[1 / 4474] Processing top level class Lcom/google/android/gms/nearby/messages/zze;
[2 / 4474] Processing top level class Lcom/google/android/gms/games/internal/zzg;
(1 / 9) Executing top level method: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;
17:50:50.267 WARN  InvokeOp     - Method had possible execution path which throws an exception but cannot instantiate it because the value is unknown. Exception item: type=Ljava/lang/UnsupportedOperationException;, value=*unknown*
Simplifying: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 2
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
(2 / 9) Executing top level method: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/games/internal/zzp;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;
17:50:50.346 WARN  InvokeOp     - Method had possible execution path which throws an exception but cannot instantiate it because the value is unknown. Exception item: type=Ljava/lang/UnsupportedOperationException;, value=*unknown*
Simplifying: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/games/internal/zzp;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 2
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
(3 / 9) Executing top level method: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;Lcom/google/android/gms/games/internal/zzo;)Lcom/google/android/gms/tasks/Task;
17:50:50.393 WARN  InvokeOp     - Method had possible execution path which throws an exception but cannot instantiate it because the value is unknown. Exception item: type=Ljava/lang/UnsupportedOperationException;, value=*unknown*
Simplifying: Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;Lcom/google/android/gms/games/internal/zzo;)Lcom/google/android/gms/tasks/Task;
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 2
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
(4 / 9) Executing top level method: Lcom/google/android/gms/games/internal/zzg;->zzah(Lcom/google/android/gms/common/api/Status;)Lcom/google/android/gms/common/api/Status;
Simplifying: Lcom/google/android/gms/games/internal/zzg;->zzah(Lcom/google/android/gms/common/api/Status;)Lcom/google/android/gms/common/api/Status;
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 0
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
(5 / 9) Executing top level method: Lcom/google/android/gms/games/internal/zzg;->zzb(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;
17:50:51.391 WARN  InvokeOp     - Method had possible execution path which throws an exception but cannot instantiate it because the value is unknown. Exception item: type=Ljava/lang/UnsupportedOperationException;, value=*unknown*
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/android/gms/games/internal/zzg;->zzb(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;)Lcom/google/android/gms/tasks/Task;, op=invoke-static {r1, r2, r0}, Lcom/google/android/gms/games/internal/zzg;->zza(Lcom/google/android/gms/common/api/PendingResult;Lcom/google/android/gms/common/internal/zzbo;Lcom/google/android/gms/games/internal/zzo;)Lcom/google/android/gms/tasks/Task;, @=1} and was not handled. This could be a bug in smalivm.
Exception: java.lang.ArrayIndexOutOfBoundsException: 0
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:187)
        at org.cf.simplify.Launcher.run(Launcher.java:151)
        at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment]
Thanks for the report. Looks like an array isn't initialized correctly.

You greatly decrease your chances of success when you try to simplify giant, complicated libraries. I don't think you need to either, since there's unlikely to be anything interested hiding in com.google.android.gms and stuff there is mostly open source, or you can find a non-obfuscated version of it elsewhere.

One of the recommendations made in the readme is to try and optimize _only_ specific parts of code that you're interested in. Are there any classes / methods you'd really like to simplify? How does simplify work on those?

**Comment by AndnixSH** [comment]
I tried to only simplify "xshield" or other names, it success but no optimization, string still obfuscated. All I want is to deobfuscate string.

The decoder seems to be in xshield.
`invoke-static {v9}, Lcom/xshield/b;->h(Ljava/lang/String;)Ljava/lang/String;`

![image](https://user-images.githubusercontent.com/40742924/46244986-5d997580-c3e7-11e8-8c4a-cb478fd85423.png)

I don't have much knowledge in smali and java.

**Comment by CalebFenton** [comment]
What class / methods, specifically, are you trying to simplify within `xshield`? I picked a small class `xshield/w` and string decryption works.

Before:
```java
public class w extends BroadcastReceiver {
    public static final String IiiIIiiIIi = b.h("x\005}\031v\002}Ep\005m\016w\0377\nz\037p\004wEJ(K.\\%F$W");
    public static final String iiIiIIIIiI = b.h("\nw\017k\004p\0177\002w\037|\005mEx\bm\002v\00578Z9\\.W4V-_");

    public w(da paramda) {}

    public void onReceive(Context paramContext, Intent paramIntent) {
        try {
            String str1 = paramIntent.getAction();
            String str2 = "\nw\017k\004p\0177\002w\037|\005mEx\bm\002v\00578Z9\\.W4V-_";
            str2 = b.h(str2);
            boolean bool = str1.equals(str2);
            if (bool) {
                str1 = "\\8M*['P8Q.]F4";
                str1 = b.h(str1);
                da.q(str1);
                return;
            }
            str1 = paramIntent.getAction();
            str2 = "x\005}\031v\002}Ep\005m\016w\0377\nz\037p\004wEJ(K.\\%F$W";
            str2 = b.h(str2);
            bool = str1.equals(str2);
            if (bool) {
                str1 = "\\8M*['P8Q.]@2";
                str1 = b.h(str1);
                da.q(str1);
                return;
            }
        } finally {
            ((Throwable) localObject).printStackTrace();
        }
    }
}
```

After:
```java
public class w
  extends BroadcastReceiver
{
  public static final String IiiIIiiIIi = "android.intent.action.SCREEN_ON";
  public static final String iiIiIIIIiI = "android.intent.action.SCREEN_OFF";
  
  public w(da paramda) {}
  
  public void onReceive(Context paramContext, Intent paramIntent)
  {
    String str1 = paramIntent.getAction();
    String str2 = "android.intent.action.SCREEN_OFF";
    boolean bool = str1.equals(str2);
    if (bool)
    {
      da.q("ESTABLISHED--");
      return;
    }
    str1 = paramIntent.getAction();
    str2 = "android.intent.action.SCREEN_ON";
    bool = str1.equals(str2);
    if (bool)
    {
      da.q("ESTABLISHED++");
      return;
    }
  }
}
```

So whatever the problem is, it's not in the decryption routine, which looks really simple anyway. Not saying there's no bug, just trying to figure out which one you're experiencing (other than the one in `com/google/android/gms/games/internal` which I don't want to prioritize since it should never be simplified)

**Comment by AndnixSH** [comment]
I'm trying to simplify all class / methods that contains encrypted strings. If you are telling me to simplify one by one, this will take long long time.
The problem is string are encrypted everywhere, I want it to decrypt all string at the same time except com/google/android/gms/games/internal of course
Please take a look at \smali\bolts and \smali\com

**Comment by CalebFenton** [comment]
Now you got me all curious -- why do you think you'll have to simplify classes one by one using a regex filter?

**Comment by AndnixSH** [comment]
Like you did but forget what I said, I misunderstand it. I found a way to exclude "com/google" but there is other problem.
Is it possible to exclude multiple REGEX? Sorry i'm new to REGEX thing. I really just want it done without problems

```
java -jar simplify-1.2.0.jar "D:\xxxx\classes.dex" -et com/google --max-call-depth 999
[1 / 4474] Processing top level class Lcom/google/android/gms/nearby/messages/zze;
[2 / 4474] Processing top level class Lcom/google/android/gms/games/internal/zzg;
[3 / 4474] Processing top level class Lcom/twitter/sdk/android/tweetcomposer/R$drawable;
(1 / 1) Executing top level method: Lcom/twitter/sdk/android/tweetcomposer/R$drawable;-><init>()V
Simplifying: Lcom/twitter/sdk/android/tweetcomposer/R$drawable;-><init>()V
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead assignments removed = 0
        dead ops removed = 0
        dead results removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        useless gotos removed = 0
[4 / 4474] Processing top level class Lcom/google/android/gms/internal/zzbgp;
[5 / 4474] Processing top level class Lcom/google/android/gms/internal/zzcbc;
[6 / 4474] Processing top level class Lcom/google/android/gms/common/api/internal/zzbw;
[7 / 4474] Processing top level class Lcom/google/gson/Gson$1;
[8 / 4474] Processing top level class Lcom/google/android/gms/flags/impl/zzj;
[9 / 4474] Processing top level class Lcom/google/android/gms/auth/api/signin/zzb;
[10 / 4474] Processing top level class Lretrofit2/OkHttpCall$ExceptionCatchingRequestBody;
(2 / 6) Executing top level method: Lretrofit2/OkHttpCall$ExceptionCatchingRequestBody;-><init>(Lokhttp3/ResponseBody;)V
Exception in thread "main" java.lang.RuntimeException: Can't find Smali file for Lokhttp3/ResponseBody;
        at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:181)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:120)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:139)
        at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:113)
        at org.cf.smalivm.type.VirtualClass.getImmediateAncestors(VirtualClass.java:60)
        at org.cf.smalivm.type.VirtualClass.getAncestors0(VirtualClass.java:46)
        at org.cf.smalivm.type.VirtualClass.getAncestors(VirtualClass.java:73)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:176)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:96)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:187)
        at org.cf.simplify.Launcher.run(Launcher.java:151)
        at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment]
The regex can be arbitrarily long and they can take the form of, say, `Lcom/pkg1/(Foo|Bar)` which will match `Lcom/pkg1/Foo` and `Lcom/pkg1/Bar`. Another example `Lcom/(pkg1/Foo|pkg2)` will match `Lcom/pkg1/Foo` and `Lcom/pkg2`, i.e. every class in `pkg2`.

The error you're getting `Can't find Smali file for Lokhttp3/ResponseBody;` is saying that smalivm didn't find that class in either the reference framework or in the input dex. My guess is that you've removed some libraries from the input dex to make it smaller, perhaps to combine multiple dex files without going over the method limit. In any case, you'll either need to exclude that input class (probably not what you want) or provide the `ResponseBody` class and all of its dependencies (and all other class dependencies of the input class).
