### ISSUE TITLE
an error when run demo

### ISSUE THREAD

**Issue by xxhong** [CalebFenton/simplify#127]
[1 / 20] Processing top level class Lorg/cf/obfuscated/Reflection;
(1 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Exception in thread "main" java.lang.RuntimeException: Error loading class definition: Landroid/icu/text/MessagePatternUtil;
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:183)
	at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:201)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:135)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:154)
	at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:128)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:109)
	at org.cf.smalivm.dex.SmaliClassLoader.loadClass(SmaliClassLoader.java:71)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
	at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:39)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:173)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:164)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:62)
	at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
	at org.cf.simplify.Launcher.run(Launcher.java:141)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:180)
	... 15 more

**Comment by xxhong** [comment]
how to fix it ?

**Comment by CalebFenton** [comment]
Did you clone recursively?
