### ISSUE TITLE
error in demo

### ISSUE THREAD

**Issue by krviolet** [CalebFenton/simplify#128]
java -jar simplify/build/libs/simplify-1.2.1.jar -it 'org/cf/obfuscated' -et 'MainActivity' simplify/obfuscated-app.apk

[1 / 19] Processing top level class Lorg/cf/obfuscated/Reflection;
(1 / 8) Executing top level method: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.rits.cloning.Cloner (file:/mnt/c/Users/user/Documents/wireshark/python_scripts/Packet_Analysis/Auto_module/apps/simplify/simplify/build/libs/simplify-1.2.1.jar) to field java.util.TreeSet.m
WARNING: Please consider reporting this to the maintainers of com.rits.cloning.Cloner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: Error loading class definition: Landroid/app/Dialog$-void__init__android_content_Context_context_int_themeResId_boolean_createContextThemeWrapper_LambdaImpl0;
        at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:183)
        at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:201)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:135)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:154)
        at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:128)
        at org.cf.smalivm.dex.ClassBuilder.visitInnerClasses(ClassBuilder.java:154)
        at org.cf.smalivm.dex.ClassBuilder.visitClassAnnotations(ClassBuilder.java:187)
        at org.cf.smalivm.dex.ClassBuilder.visitClass(ClassBuilder.java:208)
        at org.cf.smalivm.dex.ClassBuilder.build(ClassBuilder.java:64)
        at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:112)
        at org.cf.smalivm.dex.SmaliClassLoader.loadClass(SmaliClassLoader.java:71)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
        at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:113)
        at org.cf.smalivm.dex.SmaliClassLoader.loadClass(SmaliClassLoader.java:71)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
        at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:39)
        at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:173)
        at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:164)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:62)
        at org.cf.simplify.Launcher.executeMethods(Launcher.java:195)
        at org.cf.simplify.Launcher.run(Launcher.java:141)
        at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:167)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
        at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:180)
        ... 25 more

**Comment by CalebFenton** [comment]
What java version are you using?

Did you clone recursively?

**Comment by krviolet** [comment]
Yes, I clone recursively, but did't install correct JDK. Ploblem is solved

**Comment by CalebFenton** [comment]
Thanks for reporting your fix! Hopefully someone can search the same error and see the fix now.
