### ISSUE TITLE
 Multiple switch instructions refer to the same payload.

### ISSUE THREAD

**Issue by DarioI** [CalebFenton/simplify#37]
Exception in thread "main" java.lang.IllegalStateException: Multiple switch instructions refer to the same payload. This is not currently supported. Please file a bug :)
    at org.jf.dexlib2.builder.MutableMethodImplementation.fixInstructions(MutableMethodImplementation.java:392)
    at org.jf.dexlib2.builder.MutableMethodImplementation.getTryBlocks(MutableMethodImplementation.java:167)
    at org.cf.simplify.MethodBackedGraph.removeEmptyTryCatchBlocks(MethodBackedGraph.java:316)
    at org.cf.simplify.MethodBackedGraph.removeInstruction(MethodBackedGraph.java:181)
    at org.cf.simplify.MethodBackedGraph.removeInstruction(MethodBackedGraph.java:187)
    at org.cf.simplify.MethodBackedGraph.removeInstructions(MethodBackedGraph.java:195)
    at org.cf.simplify.strategy.DeadRemovalStrategy.perform(DeadRemovalStrategy.java:192)
    at org.cf.simplify.Optimizer.simplify(Optimizer.java:60)
    at org.cf.simplify.Launcher.executeClass(Launcher.java:102)
    at org.cf.simplify.Launcher.run(Launcher.java:61)
    at org.cf.simplify.Main.main(Main.java:12)

**Comment by CalebFenton** [comment]
Thanks for the error report. I think I know what can cause this and should be able to reproduce. For final testing, I'd like to run it on the same sample. Can you post the SHA1?

**Comment by Storyyeller** [comment]
One of the Enjarify test cases has multiple switch statements that point to the same payload. 

You can see it here https://github.com/google/enjarify/blob/ff815dad9daf445d2dcc35b6937e75baa988214b/tests/test3/classes.dex with the smali code https://github.com/google/enjarify/blob/ff815dad9daf445d2dcc35b6937e75baa988214b/tests/test3/smali/a/a.smali.

I had to use an old version of Smali to build it because Smali v2 doesn't let you do this.

**Comment by CalebFenton** [comment]
Interesting. I will probably need to hack around dexlib2 to make this work properly since the bug isn't really in my code. But if multiple instructions refer to the same payload, there's likely some room for optimization or it's being caused by incorrect optimization.

**Comment by CalebFenton** [comment]
I can't reproduce this issue. It could be a change I made or, more likely, a dexlib2 change. There's also a small chance I'm not running it the same way you were, but I ran several methods, including the "parent" `testSwitch()V` method.

There _is_ an error, but I think it's generated from the switch referencing an array payload as a label, which seems to confuse dexlib. This is the weird code:

```smali
:unusedSwitch
    .sparse-switch
        -0x80000000 -> :unusedSwitch
        10 -> :loopStart
        13 -> :loopEnd
        15 -> :emptyPacked
        20 -> :emptySparse
        0x7FFFFF -> :unusedData
    .end sparse-switch
:unusedData
    .array-data 2
        0 1 2 3 4 5 6 -1 -2 -3 -128
    .end array-data
```

Dexlib2 translates this as (yes, it's even commented out):

```smali
    #@3a
    # .sparse-switch
    #     -0x80000000 -> +58
    #     0xa -> +17
    #     0xd -> +48
    #     0xf -> +35
    #     0x14 -> +41
    #     0x7fffff -> +84
    # .end sparse-switch
```

This is either invalid smali or should be an issue for dexlib.
