### ISSUE TITLE
Error while loading class definition of Landroid/icu/text/MessagePatternUtil;

### ISSUE THREAD

**Issue by gaurav9991** [CalebFenton/simplify#42]
Hi, I am trying to simplify a DEX and getting this error:

`Executing: Lcom/ranfoye/agoxnhg/Rr;-><init>()V
Exception in thread "main" java.lang.RuntimeException: Error while loading class definition of Landroid/icu/text/MessagePatternUtil;
        at org.cf.smalivm.smali.ClassManager.dexifyClassIfNecessary(ClassManager.java:383)
        at org.cf.smalivm.smali.ClassManager.getClass(ClassManager.java:76)
        at org.cf.smalivm.smali.SmaliClassLoader.findClass(SmaliClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:60)
        at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:70)
        at org.cf.smalivm.VirtualMachine.spawnRootExecutionContext(VirtualMachine.java:169)
        at org.cf.smalivm.VirtualMachine.spawnRootExecutionContext(VirtualMachine.java:158)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:62)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at org.cf.smalivm.smali.Dexifier.dexifySmaliFile(Dexifier.java:42)
        at org.cf.smalivm.smali.ClassManager.dexifyClassIfNecessary(ClassManager.java:380)
        ... 12 more`

Here is the smali code for which error occured:
```
.class public Lcom/ranfoye/agoxnhg/Rr;
.super Landroid/content/BroadcastReceiver;


# direct methods
.method public constructor <init>()V
    .locals 0

    invoke-direct {p0}, Landroid/content/BroadcastReceiver;-><init>()V

    return-void
.end method
```
APK MD5: 0a868001c796c255155977d58988f8a9

**Comment by CalebFenton** [comment]
Thanks for the well formed report. I think the issue is that you need to update submodules. This file should exist:
`smalivm/src/main/resources/framework/smali/android-23/android/icu/text/MessagePatternUtil.smali`

Check if that file exists. If it doesn't exist, try this: `git submodule foreach git pull`

If it _does_ exist, try `gradle clean fatjar`, and if it still doesn't work, let me know.

**Comment by gaurav9991** [comment]
Thanks a lot it worked.
