### ISSUE TITLE
Can't simplify

### ISSUE THREAD

**Issue by HpNoTiQ56** [CalebFenton/simplify#45]
Hi,
Im trying to simplify last waze APK to get rid of signature verification. (http://www.apkmirror.com/apk/waze/waze-waze/waze-waze-4-0-0-2-release/waze-gps-maps-traffic-4-0-0-2-android-apk-download/)
When I try to simplify (I build from updated repo), I get following error.

C:\Users\****\Simplify\simplify\build\libs>java -jar simplify-1.0.0.jar "D:\
Logiciels\Reverse Engineering\URET Android Reverser Toolkit v1.2\waze_4_0_0_2"
Executing: Lcom/google/android/gms/measurement/internal/zzv$zzb;-><init>(Lcom/go
ogle/android/gms/measurement/internal/zzv;Ljava/lang/String;)V
Simplifying: Lcom/google/android/gms/measurement/internal/zzv$zzb;-><init>(Lcom/
google/android/gms/measurement/internal/zzv;Ljava/lang/String;)V
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead ops removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        unused assignments removed = 0
        unused results removed = 1
        useless gotos removed = 0
Executing: Lcom/google/android/gms/measurement/internal/zzv$zzb;->uncaughtExcept
ion(Ljava/lang/Thread;Ljava/lang/Throwable;)V
21:01:30.289 WARN  InvokeOp     - Cannot execute local native method: Landroid/u
til/Log;->isLoggable(Ljava/lang/String;I)Z. Assuming maxiumum ambiguity.
21:04:40.937 WARN  InvokeOp     - org.cf.smalivm.exception.MaxAddressVisitsExcee
ded: Exceeded max address visits @250 ExecutionNode{signature=Lcom/google/androi
d/gms/measurement/internal/zzp;->zzc(ZLjava/lang/Object;)Ljava/lang/String;, op=
invoke-virtual {r3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;} in
 Lcom/google/android/gms/measurement/internal/zzp;->zzc(ZLjava/lang/Object;)Ljav
a/lang/String;
21:07:32.881 WARN  InvokeOp     - org.cf.smalivm.exception.MaxAddressVisitsExcee
ded: Exceeded max address visits @250 ExecutionNode{signature=Lcom/google/androi
d/gms/measurement/internal/zzp;->zzc(ZLjava/lang/Object;)Ljava/lang/String;, op=
invoke-virtual {r3}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;} in
 Lcom/google/android/gms/measurement/internal/zzp;->zzc(ZLjava/lang/Object;)Ljav
a/lang/String;
21:07:32.881 WARN  InvokeOp     - org.cf.smalivm.exception.MaxExecutionTimeExcee
ded: Exceeded execution time in Lcom/google/android/gms/measurement/internal/zzp
;->zza(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;
)Ljava/lang/String;
21:07:32.882 WARN  InvokeOp     - org.cf.smalivm.exception.MaxExecutionTimeExcee
ded: Exceeded execution time in Lcom/google/android/gms/measurement/internal/zzp
;->zza(IZZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Objec
t;)V
21:07:32.882 WARN  InvokeOp     - org.cf.smalivm.exception.MaxExecutionTimeExcee
ded: Exceeded execution time in Lcom/google/android/gms/measurement/internal/zzp
$zza;->zzm(Ljava/lang/String;Ljava/lang/Object;)V
Aborting execution: org.cf.smalivm.exception.MaxExecutionTimeExceeded: Exceeded
execution time in Lcom/google/android/gms/measurement/internal/zzv$zzb;->uncaugh
tException(Ljava/lang/Thread;Ljava/lang/Throwable;)V
Skipping Lcom/google/android/gms/measurement/internal/zzv$zzb;->uncaughtExceptio
n(Ljava/lang/Thread;Ljava/lang/Throwable;)V
Executing: Lcom/google/android/gms/internal/zzafh$1;->zza(Lcom/google/android/gm
s/common/api/Status;Ljava/lang/Object;Ljava/lang/Integer;J)V
21:07:33.658 WARN  NodeExecutor - ExecutionNode{signature=Lcom/google/android/gm
s/common/api/Status;-><init>(ILjava/lang/String;)V, op=invoke-direct {r2, r0, r3
, r4, r1}, Lcom/google/android/gms/common/api/Status;-><init>(IILjava/lang/Strin
g;Landroid/app/PendingIntent;)V} threw a real exception:
java.lang.RuntimeException: Stub!
        at com.google.android.gms.common.api.Status.hashCode(Unknown Source)
        at org.apache.commons.lang3.builder.HashCodeBuilder.append(HashCodeBuild
er.java:859)
        at org.cf.smalivm.context.HeapItem.hashCode(HeapItem.java:105)
        at java.util.HashMap.hash(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at java.util.HashSet.add(Unknown Source)
        at org.cf.smalivm.context.ExecutionGraph.getRegisterItems(ExecutionGraph
.java:377)
        at org.cf.smalivm.context.ExecutionGraph.getRegisterConsensus(ExecutionG
raph.java:325)
        at org.cf.smalivm.context.ExecutionGraph.getTerminatingRegisterConsensus
(ExecutionGraph.java:443)
        at org.cf.smalivm.context.ExecutionGraph.getTerminatingRegisterConsensus
(ExecutionGraph.java:434)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:337)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNe
cessary(ExecutionContext.java:232)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:92)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
21:07:33.661 WARN  NodeExecutor - ExecutionNode{signature=Lcom/google/android/gm
s/common/api/Status;-><init>(I)V, op=invoke-direct {r1, r2, r0}, Lcom/google/and
roid/gms/common/api/Status;-><init>(ILjava/lang/String;)V} threw a real exceptio
n:
java.lang.NullPointerException: null
        at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.
java:397)
        at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNe
cessary(ExecutionContext.java:232)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:92)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
21:07:33.665 WARN  NodeExecutor - ExecutionNode{signature=Lcom/google/android/gm
s/common/api/Status;-><clinit>()V, op=invoke-direct {r0, r1}, Lcom/google/androi
d/gms/common/api/Status;-><init>(I)V} threw a real exception:
java.lang.NullPointerException: null
        at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.
java:397)
        at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNe
cessary(ExecutionContext.java:232)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:92)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
21:07:33.670 WARN  NodeExecutor - ExecutionNode{signature=Lcom/google/android/gm
s/internal/zzafh$1;->zza(Lcom/google/android/gms/common/api/Status;Ljava/lang/Ob
ject;Ljava/lang/Integer;J)V, op=invoke-virtual {r9}, Lcom/google/android/gms/com
mon/api/Status;->isSuccess()Z} threw a real exception:
java.lang.NullPointerException: null
        at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.
java:397)
        at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNe
cessary(ExecutionContext.java:232)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:92)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:77)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:310)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:134)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:53)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
Exception in thread "main" java.lang.NullPointerException
        at org.cf.smalivm.context.ExecutionGraph.getTemplateNode(ExecutionGraph.
java:397)
        at org.cf.smalivm.NodeExecutor.spawnChild(NodeExecutor.java:51)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:39)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)
Maybe I've done something wrong (I've unpacked apk with apktool).

**Comment by CalebFenton** [comment]
I don't think you've done anything wrong. There are some operations which really can't be emulated, and across an entire application, you're bound to hit at least one.

It might be a while before I can fully dive into this, so while you wait, I suggest limiting the scope of simplify to just the classes you care about and see what happens.

**Comment by CalebFenton** [comment]
Closing this issue since there have been many recent changes which may have affected this. Please feel free to re-open if you still have issues.
