### ISSUE TITLE
Simplify fails to deobfuscate

### ISSUE THREAD

**Issue by ShoubhikRaj** [CalebFenton/simplify#46]
I am running simplify on a directory containing smali files using the command `java -jar simplify.jar ./smali -o out.dex` and I am getting the following error:

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
        at java.util.concurrent.ConcurrentHashMap.putIfAbsent(Unknown 

Source
        at com.rits.cloning.Cloner.allFields(Cloner.java:549)
        at com.rits.cloning.Cloner.registerStaticFields(Cloner.java:180)
        at com.rits.cloning.Cloner.registerKnownConstants

(Cloner.java:166)
        at com.rits.cloning.Cloner.init(Cloner.java:83)
        at com.rits.cloning.Cloner.<init>(Cloner.java:59)
        at org.cf.smalivm.context.HeapItem.<init>(HeapItem.java:21)
        at org.cf.smalivm.context.Heap.cloneItem(Heap.java:139)
        at org.cf.smalivm.context.Heap.get(Heap.java:49)
        at org.cf.smalivm.context.Heap.get(Heap.java:69)
        at org.cf.smalivm.context.BaseState.peekRegister

(BaseState.java:87)
        at org.cf.smalivm.context.BaseState.readRegister

(BaseState.java:108)
        at org.cf.smalivm.context.MethodState.readRegister

(MethodState.java:

        at org.cf.smalivm.opcode.IfOp.execute(IfOp.java:69)
        at org.cf.smalivm.context.ExecutionNode.execute

(ExecutionNode.java:5
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
        at org.cf.simplify.Launcher.run(Launcher.java:69)
        at org.cf.simplify.Main.main(Main.java:14)

**Comment by CalebFenton** [comment]
The java virtual machine ran out of heap space. The data structures that record the execution of the app can get quite large. There's probably not a bug to fix; the only thing that I can change to optimize, and I'm not ready to optimize.

You have a few options.

The first, and easiest, is to just assign more heap space to the jvm.

The second option is to run with verbose mode, discover the method that is taking up all the heap space and exclude it.

The third option is to **only** optimize the methods you care about. Otherwise, optimization may overflow the heap or crash at some random bit of code you don't care about.

**Comment by ShoubhikRaj** [comment]
I will try to run it by increasing the heap space. While I am at it, please let me know how I can run simplify on specific methods.
Another thing I would like to point out is that after getting the above error, I ran simplify on dex files of 3 other apps. It failed to complete the deobfuscation process every time. One of the dex file was only 20kb and it failed at even that. So, please make some changes (I am not suggesting any specific change) so that it can complete the process. Time is not a factor here. But whether the task is completed or not is the key point.

**Comment by CalebFenton** [comment]
RTFM

**Comment by ShoubhikRaj** [comment]
I am really sorry. I understand it now.

**Comment by CalebFenton** [comment]
No problem. It's easier for me to help if I know you're helping yourself.

**Comment by ShoubhikRaj** [comment]
Sorry for bothering you again.
 I increased the heap space to its maximum using -Xmx but it only delayed the error. So, I have a suggestion. I think that it might be be possible to write the log of smalivm to a file on hard disk and then read from the log or use some mechanism which uses the hard disk to store the overflow from heap.
 I don't whether implementing this would be possible or not, but you can always experiment with options.

**Comment by CalebFenton** [comment]
It would probably be possible to get something working decently that serialized stuff to disk whenever there was too much of it to fit in heap, as you're suggesting. I haven't done much optimization, apart from the super obvious, because correctness is still my main concern. I think there are some optimizations that would reduce the heap requirement, but they would make the code more complex and difficult to debug.

In the mean time, you can try a few things like not optimizing the method that's causing all the trouble or by limiting the max address visits, etc. This stuff is somewhat covered in the readme, but if you have problems or something isn't clear, just ask and I can make the readme more clear.

**Comment by ShoubhikRaj** [comment]
I have one question:
If I run simplify without any -output tag, then does it apply the modifications to the smali files itself ?
I have read the readme and it seems that it does, but I just want to make sure.
Thank you again.

**Comment by CalebFenton** [comment]
Good question. No, it'll name the output file for you. Smali is never
modified, only dex.

My other project https://github.com/CalebFenton/dex-oracle modifies smali.
It complements simplify by having little overlap in strengths and
weaknesses.

**Comment by ShoubhikRaj** [comment]
Thank you.

**Comment by nurisezginspexco** [comment]
Hi,
I need same situation about my problem with simplify during deobfuscate Android app. I got exception. (Full detail about exception paste end of the message which one is start with '1)'.) Then i exclude this error items. Added running options with use -ex 'com.dropbox'. After all i got new exception with "NoSuchFieldError" title.(Full detail about exception paste end of the message which one is start with '2') Last time i exculede these packages together with use -ex 'com.dropbox|b.a.a.a.d' result exception changed.

"" Exception in thread "main" java.lang.IllegalArgumentException: No implementation for Lc/a/b/p;->a(Lc/a/b/o;Lc/a/b/j/d;)V
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:193)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:186)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:87)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
""

Its very important for me. Could you help me? Thank you.

1) Exception in thread "main" java.lang.NoSuchFieldError: $VALUES
	at com.dropbox.client2.c.n.<clinit>(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
	at java.lang.Class.enumConstantDirectory(Class.java:3341)
	at java.lang.Enum.valueOf(Enum.java:232)
	at org.cf.smalivm.ObjectInstantiator.newEnumInstance(ObjectInstantiator.java:48)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:18)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:397)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:68)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:206)
	at org.cf.smalivm.context.ExecutionContext.readClassState(ExecutionContext.java:133)
	at org.cf.smalivm.StaticFieldAccessor.getLocalField(StaticFieldAccessor.java:32)
	at org.cf.smalivm.StaticFieldAccessor.getField(StaticFieldAccessor.java:27)
	at org.cf.smalivm.opcode.SGetOp.execute(SGetOp.java:39)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:206)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:124)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)

2) Exception in thread "main" java.lang.NoSuchFieldError: $VALUES
	at b.a.a.a.d.<clinit>(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.lang.Class.getEnumConstantsShared(Class.java:3320)
	at java.lang.Class.enumConstantDirectory(Class.java:3341)
	at java.lang.Enum.valueOf(Enum.java:232)
	at org.cf.smalivm.ObjectInstantiator.newEnumInstance(ObjectInstantiator.java:48)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:18)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:397)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:68)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:206)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:124)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)

**Comment by CalebFenton** [comment]
@nurisezginspexco thanks for reporting the error. Could you create a new issue and also post some relevant details that'll allow me to attempt to reproduce the issue. E.g. either the dex, apk, or a file hash of the apk if you can't share the file.

**Comment by nurisezginspexco** [comment]
I attached source apk file.
[base.zip](https://github.com/CalebFenton/simplify/files/487580/base.zip)

**Comment by CalebFenton** [comment]
Create a new issue. This one is closed.

**Comment by CalebFenton** [comment]
Create new issue, add details, thanks
