### ISSUE TITLE
obfuscated-example not working

### ISSUE THREAD

**Issue by w4nd** [CalebFenton/simplify#48]
Hi,

I am trying to run simplify against the obfuscated-example with:
$java -jar simplify/build/libs/simplify.jar -it 'org/cf' simplify/obfuscated-example
The following error occurs:

"""
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead ops removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	unused assignments removed = 0
	unused results removed = 0
	useless gotos removed = 0
Executing: Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Aborting execution: org.cf.smalivm.exception.MaxExecutionTimeExceeded: Exceeded execution time in Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Skipping Lorg/cf/obfuscated/XORCrypt;->encode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Executing: Lorg/cf/obfuscated/XORCrypt;->decode(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.lang.reflect.Field.copy(Field.java:150)
	at java.lang.reflect.ReflectAccess.copyField(ReflectAccess.java:144)
	at sun.reflect.ReflectionFactory.copyField(ReflectionFactory.java:309)
	at java.lang.Class.copyFields(Class.java:3115)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.rits.cloning.Cloner.allFields(Cloner.java:543)
	at com.rits.cloning.Cloner.registerStaticFields(Cloner.java:180)
	at com.rits.cloning.Cloner.registerKnownConstants(Cloner.java:166)
	at com.rits.cloning.Cloner.init(Cloner.java:83)
	at com.rits.cloning.Cloner.<init>(Cloner.java:59)
	at org.cf.smalivm.context.HeapItem.<init>(HeapItem.java:21)
	at org.cf.smalivm.context.Heap.cloneItem(Heap.java:139)
	at org.cf.smalivm.context.Heap.get(Heap.java:49)
	at org.cf.smalivm.context.Heap.get(Heap.java:69)
	at org.cf.smalivm.context.BaseState.peekRegister(BaseState.java:87)
	at org.cf.smalivm.context.BaseState.readRegister(BaseState.java:108)
	at org.cf.smalivm.context.MethodState.readRegister(MethodState.java:156)
	at org.cf.smalivm.opcode.BinaryMathOp.execute(BinaryMathOp.java:72)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:51)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:31)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:66)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:99)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:101)
	at org.cf.simplify.Launcher.run(Launcher.java:69)
	at org.cf.simplify.Main.main(Main.java:14)
"""

Using
$export JVM_ARGS="-XX:-UseGCOverheadLimit -Xms1024m -Xmx1024m"
Here, any guess on what is going wrong?
Thanks

**Comment by strazzere** [comment]
This example world fine for me when building and pulling from `HEAD` - what are the specs on your machine?

You might want to raise the max memory to something larger to ensure it doesn't run out of space. On my MBP I noticed it using upwards of 4096mb of memory.

**Comment by CalebFenton** [comment]
Raising max memory is unfortunately the solution. Smalivm stores the entire context sensitive graph in memory while it's optimized.

Some optimizations are possible but I'm still focused on correctness and fixing bugs before I start confusing things with too many optimizations.

**Comment by w4nd** [comment]
Hi, just give a reply on the issue, thank you very much, I could test it today and simplify works with more memory, something like 7MB is enough for everything i've tryied.
