### ISSUE TITLE
Caused by: java.lang.RuntimeException: Unrecognized type: ?

### ISSUE THREAD

**Issue by brainblowjob** [CalebFenton/simplify#53]
I'm tried `java -classpath smalivm-1.2.0.jar  -jar simplify-1.2.0.jar classes.dex`

and this don't work for me

Log

> 03:33:02.867 WARN  SmaliFileFactory - Input class 'Landroid/content/pm/PackageStats$1;' has an earlier definition; ignoring
03:33:02.869 WARN  SmaliFileFactory - Input class 'Landroid/content/pm/PackageStats;' has an earlier definition; ignoring
03:33:02.869 WARN  SmaliFileFactory - Input class 'Landroid/content/pm/IPackageStatsObserver$Stub;' has an earlier definition; ignoring
03:33:02.869 WARN  SmaliFileFactory - Input class 'Landroid/content/pm/IPackageStatsObserver;' has an earlier definition; ignoring
03:33:02.869 WARN  SmaliFileFactory - Input class 'Landroid/content/pm/IPackageStatsObserver$Stub$Proxy;' has an earlier definition; ignoring
Executing: Lcom/google/a/b/w;->a(Ljava/lang/Object;Ljava/lang/Object;)Z
Simplifying: Lcom/google/a/b/w;->a(Ljava/lang/Object;Ljava/lang/Object;)Z
Optimizations:
        constantized ifs = 0
        constantized ops = 0
        dead ops removed = 0
        nops removed = 0
        peephole optmizations = 0
        unreflected fields = 0
        unreflected methods = 0
        unused assignments removed = 0
        unused results removed = 0
        useless gotos removed = 0
Executing: Lcom/google/a/b/w;->remove(Ljava/lang/Object;)Ljava/lang/Object;
03:33:06.924 WARN  InvokeOp     - org.cf.smalivm.MaxAddressVisitsExceededException: Exceeded max address visits @26 ExecutionNode{signature=Lcom/google/a/b/w;->find(Ljava/lang/Object;Z)Lcom/google/a/b/ad;, op=return-object r1} in Lcom/google/a/b/w;->find(Ljava/lang/Object;Z)Lcom/google/a/b/ad;
03:33:06.926 WARN  ExecutionGraph - Consensus has multiple types! Returning unknown type.
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/a/b/w;->remove(Ljava/lang/Object;)Ljava/lang/Object;, op=invoke-virtual {r1, r2}, Lcom/google/a/b/w;->removeInternalByKey(Ljava/lang/Object;)Lcom/google/a/b/ad;} and was not handled. This could be a bug in smalivm.
Exception:
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
        at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
        at org.cf.simplify.Launcher.run(Launcher.java:153)
        at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/a/b/w;->removeInternalByKey(Ljava/lang/Object;)Lcom/google/a/b/ad;, op=invoke-virtual {r2, r0, r1}, Lcom/google/a/b/w;->removeInternal(Lcom/google/a/b/ad;Z)V} and was not handled. This could be a bug in smalivm.
Exception:
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
        at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
        at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
        at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
        ... 6 more
**Caused by: java.lang.RuntimeException: Unrecognized type: ?
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:125)
        at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:132)
        at org.cf.smalivm.opcode.InvokeOp.analyzeParameterTypes(InvokeOp.java:219)
        at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:82)
        at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
        at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)**
        ... 13 more

**Comment by brainblowjob** [comment]
Any ideas, @CalebFenton ?

**Comment by CalebFenton** [comment]
Try removing smalivm from the classpath. It's already included in simplify jar. I had it separated out so people could use it without using simplify.

```bash
java -jar simplify-1.2.0.jar classes.dex
```

Also, when you run into trouble running an entire dex file, try the trouble shooting section of the readme. There are a few tips there. Feel free to follow up here if you find an issue running it as mentioned above.
