### ISSUE TITLE
Method onProvideKeyboardShortcuts in class android/view/Window$Callback has illegal modifiers: 0x1

### ISSUE THREAD

**Issue by unoexperto** [CalebFenton/simplify#58]
Well, I'm sorry for spamming so much with updates but I've learned a lot since I wrote original issue :)

I built `simplify` for  API 25 to run it against my code. Version 23 didn't work because of missing `Ljava/security/MessageDigest$Delegate;`

[mysmali.zip](https://github.com/CalebFenton/simplify/files/602356/mysmali.zip) contains two smali files. I wrote Java class that executes method from it.

```
import org.cf.smalivm.VirtualMachine;
import org.cf.smalivm.VirtualMachineException;
import org.cf.smalivm.VirtualMachineFactory;
import org.cf.smalivm.context.ExecutionContext;
import org.cf.smalivm.context.ExecutionGraph;
import org.cf.smalivm.context.HeapItem;
import org.cf.smalivm.context.MethodState;

import java.io.IOException;
import java.util.ArrayList;

public class JavaMain {

    private static VirtualMachine vm;

    public static void main(String[] args) {
        String publicKey = "fa27213dcb31146fedc0abd8401bdc32da56e95d";
        String privateKey = "093b5723146caba53951cca1c0fc3c3a06a006f6";

        ArrayList<String> params = new ArrayList<>();
        params.add(publicKey);
        params.add(privateKey);
        params.add("search-translation-languages");

        // The SMALI_PATH directory is populated using dumpSmali.sh and contains converted code from org.cf.demosmali.
        // You can use a link to a DEX, APK, or directory with Smali files.
        VirtualMachineFactory vmFactory = new VirtualMachineFactory();
        try {
            vm = vmFactory.build("/home/expert/work/sideprojects/simplify/mysmali");
            executeParameterLogicWithKnownParameter(params);
        } catch (IOException | VirtualMachineException e) {
            e.printStackTrace();
        }
    }

    private static void executeParameterLogicWithKnownParameter(ArrayList<String> params) throws VirtualMachineException {
        String methodSignature = "Lcom/example/aq;->a(Ljava/util/ArrayList;)Ljava/lang/String;";
        ExecutionContext context = vm.spawnRootContext(methodSignature);
        MethodState mState = context.getMethodState();

        mState.assignParameter(mState.getParameterStart(), params, "Ljava/util/ArrayList;");
        ExecutionGraph graph = vm.execute(methodSignature, context);

        HeapItem item = graph.getTerminatingRegisterConsensus(MethodState.ReturnRegister);
        System.out.println("With context, returns " + "????" + ": " + item);
    }
}

```

It doesn't work because I get following errors

```
03:05:44.215 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x509/tsp/PKIStatus;
03:05:44.559 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/Http2;
03:05:44.605 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Boolean;
03:05:44.630 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/NativePluralRules;
03:05:44.912 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Enumerated;
03:05:44.962 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/utils/Array;
03:05:45.058 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Any;
03:05:45.080 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/DerInputStream;
03:05:45.099 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/Spdy3;
Exception in thread "main" java.lang.ClassFormatError: Method onProvideKeyboardShortcuts in class android/view/Window$Callback has illegal modifiers: 0x1
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:82)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
	at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:40)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:196)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:186)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:87)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
```

Two questions:

1) Is  there anything we could do to simulate `java.security` ?
2)  Why `android/view/Window$Callback` class is used here ?

**Comment by CalebFenton** [comment]
No need to apologize for making issues. I appreciate the time you take to write up good feedback, and you're trying to solve the issues instead of just asking for help, so it's really fine!

As to #2, it should be fixed as of https://github.com/CalebFenton/simplify/commit/c195a49ac633668c2c13062b87d74425ae4d6c11. Try again with the latest commits?

By the way, `Ljava/security/MessageDigest;` should be reflected since it's in https://github.com/CalebFenton/simplify/blob/master/smalivm/src/main/resources/safe_classes.cfg#L69. There might be some weirdness if an input smali class tries to explicitly reference an inner class of a reflected class. Let me know if you have trouble.

**Comment by unoexperto** [comment]
Thank you!!

`android/view/Window$Callback` went away with new build. Here is what I get in log now

```
expert@expert-x220:~/work/sideprojects/test$ java -jar simplify-1.1.0.jar mysmali.dex
Executing: Lcom/example/aq;->a(Ljava/util/ArrayList;)Ljava/lang/String;
14:48:29.771 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x509/tsp/PKIStatus;
14:48:30.214 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/Http2;
14:48:30.279 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Boolean;
14:48:30.313 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/NativePluralRules;
14:48:30.721 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Enumerated;
14:48:30.763 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/utils/Array;
14:48:30.905 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Any;
14:48:30.931 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/DerInputStream;
14:48:30.946 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/Spdy3;
14:48:31.134 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/net/url/UrlUtils;
14:48:31.206 ERROR ClonerFactory - Unable to load immutable class (not found): Ldalvik/annotation/TestLevel;
14:48:31.268 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/utils/AlgNameMapper;
14:48:31.273 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Set;
14:48:31.361 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/RuleBasedCollatorICU;
14:48:31.499 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x509/Time;
14:48:31.516 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/Hpack;
14:48:31.571 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x509/tsp/PKIFailureInfo;
14:48:31.593 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/CollationElementIteratorICU;
14:48:31.651 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/HeadersMode;
14:48:31.651 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Integer;
14:48:31.665 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/NativeNormalizer;
14:48:31.741 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/reflect/AnnotationAccess;
14:48:31.775 ERROR ClonerFactory - Unable to load immutable class (not found): Lcom/android/okhttp/internal/spdy/ErrorCode;
14:48:31.776 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x501/DirectoryString;
14:48:31.872 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/x509/PolicyQualifierInfo;
14:48:31.882 ERROR ClonerFactory - Unable to load immutable class (not found): Lorg/apache/harmony/security/asn1/ASN1Exception;
14:48:31.937 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/NativeIDN;
14:48:31.963 ERROR ClonerFactory - Unable to load immutable class (not found): Llibcore/icu/NativeCollation;
14:48:32.095 WARN  MethodReflector - Failed to reflect Ljava/lang/String;->substring(II)Ljava/lang/String;: null
14:48:32.099 ERROR NodeExecutor - ExecutionNode{signature=Lcom/example/aq;->a(Ljava/util/ArrayList;)Ljava/lang/String;, op=invoke-virtual {r1, r0, r2}, Ljava/lang/String;->substring(II)Ljava/lang/String;} unhandled virtual exception: {}
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:278)
	at org.cf.smalivm.MethodReflector.invoke(MethodReflector.java:115)
	at org.cf.smalivm.MethodReflector.reflect(MethodReflector.java:33)
	at org.cf.smalivm.opcode.InvokeOp.executeNonLocalMethod(InvokeOp.java:420)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:99)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	... 17 common frames omitted
Aborting execution; exception: Unhandled virtual exception: java.lang.reflect.InvocationTargetException
Skipping Lcom/example/aq;->a(Ljava/util/ArrayList;)Ljava/lang/String;
Executing: Lcom/example/e;->c(Ljava/lang/String;)Ljava/lang/String;
Aborting execution; exception: org.cf.smalivm.MaxAddressVisitsExceededException: Exceeded max address visits @50 ExecutionNode{signature=Lcom/example/e;->c(Ljava/lang/String;)Ljava/lang/String;, op=invoke-virtual {r6, r0}, Ljava/lang/StringBuilder;->append(C)Ljava/lang/StringBuilder;} in Lcom/example/e;->c(Ljava/lang/String;)Ljava/lang/String;
Skipping Lcom/example/e;->c(Ljava/lang/String;)Ljava/lang/String;
Simplified 2 methods from 2 classes in 4565 ms.
Total optimizations:

Writing output to mysmali_simple.dex
```

Are these exceptions to be expected  ?

Also resulting smali files hasn't changed (= hasn't been simplified). Is it expected behavior for my example ?

**Comment by unoexperto** [comment]
I rerun it as `java -jar simplify-1.1.0.jar -v 2 mysmali.dex >simplify_detailed.log` with detailed log. It's attached 
[here](https://github.com/CalebFenton/simplify/files/603454/simplify_detailed.log.zip)

**Comment by CalebFenton** [comment]
Could you clean and rebuild with latest changes? I may have inadvertently fixed your issue.

FYI, the output I get with your program is:

```
With context, returns ????: type=Ljava/lang/String;, value=ad1ce5c6e730bdebef946ecac594f609046cf4fa
```
