### ISSUE TITLE
"Real exception was thrown executing ExecutionNode{...} and was not handled. This could be a bug in smalivm."

### ISSUE THREAD

**Issue by Lanchon** [CalebFenton/simplify#61]
hi!

using simplify v1.1.0 release. this a dexguarded dex, AFAICT.
any pointers? would using master branch instead of release help?

thanks!

```
$ dex-simplify classes.dex -o s.dex --output-api-level 23

Executing: Lcom/localytics/android/R$dimen;-><init>()V
Simplifying: Lcom/localytics/android/R$dimen;-><init>()V
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead ops removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	unused assignments removed = 0
	unused results removed = 0
	useless gotos removed = 0
Executing: Lcom/google/android/gms/common/zzc$zzac;-><clinit>()V
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/android/gms/common/zzc$zzac;-><clinit>()V, op=invoke-direct {r1, r2}, Lcom/google/android/gms/common/zzc$zzac$1;-><init>([B)V} and was not handled. This could be a bug in smalivm.
Exception:
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:206)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:124)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:186)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/android/gms/common/zzc$zzac$1;-><init>([B)V, op=invoke-direct {r0, r1}, Lcom/google/android/gms/common/zzc$zzc;-><init>([B)V} and was not handled. This could be a bug in smalivm.
Exception:
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	... 8 more
Caused by: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/google/android/gms/common/zzc$zzc;-><init>([B)V, op=invoke-direct {r1, r2}, Lcom/google/android/gms/common/zzc$zza;-><init>([B)V} and was not handled. This could be a bug in smalivm.
Exception:
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	... 15 more
Caused by: java.lang.RuntimeException: Stub!
	at com.google.android.gms.common.zzc$zza.hashCode(Unknown Source)
	at org.apache.commons.lang3.builder.HashCodeBuilder.append(HashCodeBuilder.java:859)
	at org.cf.smalivm.context.HeapItem.hashCode(HeapItem.java:96)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at org.cf.smalivm.context.ExecutionGraph.getRegisterItems(ExecutionGraph.java:372)
	at org.cf.smalivm.context.ExecutionGraph.getRegisterConsensus(ExecutionGraph.java:324)
	at org.cf.smalivm.context.ExecutionGraph.getTerminatingRegisterConsensus(ExecutionGraph.java:439)
	at org.cf.smalivm.context.ExecutionGraph.getTerminatingRegisterConsensus(ExecutionGraph.java:430)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:380)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	... 22 more
```

**Comment by Lanchon** [comment]
adding ` -et "com/google/android/gms/"` results in different thing `java.lang.NoSuchFieldError: $VALUES`. i guess i'll keep on excluding.

**Comment by CalebFenton** [comment]
The `$VALUES` error was fixed somewhat recently but there hasn't been a new release. Can you build from master and see how that goes? Also, if you have the APK hash I might be able to reproduce the issue myself and fix it.

**Comment by Lanchon** [comment]
i saw the commit but thought that didn't apply because `ENUM$VALUES` was not being accessed.

for now excluding one thing leads to another exception and so forth. im using [this apk](https://apkpure.com/grindr-gay-chat-meet-date/com.grindrapp.android) version [3.0.8](https://apkpure.com/grindr-gay-chat-meet-date/com.grindrapp.android/download?from=details%2Fversion&fid=c%2FAPK%2F3056%2F0353e63a57aaa5a2&version_code=14016) (because latest is multi-dex). i'm processing the packages of interest only `-it '^Lcom/grindrapp/'`.

**Comment by Lanchon** [comment]
it is dexguarded, so i'm considering using dex-oracle instead. but i rather use simplify.

**Comment by Lanchon** [comment]
question, wouldn't it be better to keep going with the next method if virtual execution of a method fails? right now processing ends, this isn't that good for real-world usage.

**Comment by CalebFenton** [comment]
That sounds fine. Should I expect a PR?

**Comment by Lanchon** [comment]
i wasn't dying to dive into your code for such a simple change!
