### ISSUE TITLE
Unable to load prohibited class name: java.util.HashMap$HashMapEntry

### ISSUE THREAD

**Issue by gulizseray** [CalebFenton/simplify#62]
This is the command I'm executing:
java -jar simplify/build/libs/simplify.jar -it 'com/viber' ../Desktop/Viber/smali/Viber/smali/

Here is the apk file:
https://drive.google.com/file/d/0B4BaXMhEPliBTlBGa1Y0OXU1Z0U/view?usp=sharing

This is the error I'm getting:
```
Executing: Lcom/viber/voip/viberout/c;-><init>()V
15:50:31.564 WARN  SmaliClassLoader - Unable to load prohibited class name: java.util.HashMap$HashMapEntry
This error is likely the result of using a class which references a java.* class only available on Android. There's no work-around at this time since loading protected classes is a huge pain.
15:50:31.568 WARN  SmaliClassLoader - Unable to load prohibited class name: java.util$HashMap$HashMapEntry
This error is likely the result of using a class which references a java.* class only available on Android. There's no work-around at this time since loading protected classes is a huge pain.
15:50:31.586 ERROR NodeExecutor - ExecutionNode{signature=Ljava/util/HashMap;-><clinit>()V, op=new-array r0, r0, [Ljava/util/HashMap$HashMapEntry;} unhandled virtual exception: {}
java.lang.ClassNotFoundException: java.util.HashMap$HashMapEntry
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:71)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:923)
	at org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:957)
	at org.cf.util.Utils.buildArray(Utils.java:47)
	at org.cf.smalivm.opcode.NewArrayOp.buildInstance(NewArrayOp.java:59)
	at org.cf.smalivm.opcode.NewArrayOp.execute(NewArrayOp.java:34)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:50)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:206)
	at org.cf.smalivm.context.ExecutionContext.readClassState(ExecutionContext.java:133)
	at org.cf.smalivm.opcode.NewInstanceOp.execute(NewInstanceOp.java:37)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:109)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:327)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:136)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
15:50:31.587 WARN  ExecutionContext - Unhandled virtual exception: java.lang.ClassNotFoundException: java.util.HashMap$HashMapEntry
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/viber/voip/viberout/c;-><init>()V, op=invoke-direct {r0}, Lcom/viber/jni/dialer/DialerLocalCallStateListener;-><init>()V} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/viber/jni/dialer/DialerLocalCallStateListener;-><init>()V, op=invoke-direct {r0}, Lcom/viber/jni/controller/ControllerListener;-><init>()V} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lcom/viber/jni/controller/ControllerListener;-><init>()V, op=new-instance r0, Ljava/util/LinkedHashMap;} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:131)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:89)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment]
Thanks for the well formed report. This may be something as simple as adjusting the white list. I'll probably be able to check it out this weekend.

**Comment by CalebFenton** [comment]
Digging into this has been rewarding. Found some new bugs. Understand the JVM a bit better.

The first problem was that LinkedHashMap was inexplicably not whitelisted. (fixed https://github.com/CalebFenton/simplify/commit/8302b116f19a26bb8d912202f9ebf91e3b0f33eb)

That revealed a new problem which is that Enum classes were not properly instantiated. I was trying to use reflection but the JVM specifically prohibits what I was trying to do. The initial fix (and test!) was pretty simple. (fixed https://github.comf/CalebFenton/simplify/commit/170afe16990093125df39ec7ef88739e2ca5e930)

But this fix revealed a more tricky bug. See, the enum class it's having a problem with is `Lcom/viber/voip/o$d;`. It's kind of unusual. By default, the JVM produces enum classes with a synthetic field called `$VALUES` which is an array of all the enum field values. This `o$d` class has been obfuscated by proguard, looks like, and all the field names have been changed, including `$VALUES`. The problem was that this field name was assumed to always be the same and was hardcoded. I needed to figure out how to dynamically determine what the field name was supposed to be. (fixed https://github.com/CalebFenton/simplify/commit/ec6363cbfb2a9297c52913e6ff8259e17db9276f#diff-7035e1e149d2622af72bac7e33cea1b1R314) Also, the field names are supposed to correspond to the string name of the enum, but they didn't anymore. So I had to add `EnumAnalyzer` to try and guess the mappings from original name to the "obfuscated" name.

Unfortunately, the code still bombs out, but this is to be expected because you're trying to virtually execute what's technically referred to as a "shitload of code". I'll continue playing with this sample and mining it for new bugs, but while you're waiting for what will probably be the heat death of the universe for me to contrive what is essentially an insane replica of the entire Java Virtual Machine, you could try limiting your ambitions to just a few classes or methods you're most interested in.
