### ISSUE TITLE
VM resiliance

### ISSUE THREAD

**Issue by RomanHargrave** [CalebFenton/simplify#64]
I am currently trying to analyze an application protected with an early version of APKProtect. The application is not encrypted, but does contain string obfuscation which is sensitive to D2J (so I can't attempt to perform string deobfuscation with dynamic analysis in a JVM), and invalid Dalvik instructions inserted at some points. These invalid instructions make dexlib pretty unhappy (apktool has this problem too, since it uses dexlib). It would be nice if an in-tree change could be made such that these errors can be ingored (d2j goes about this by replacing the enclosing method with a stub, instead of exiting). Since this is an easy tactic for obfuscators, it seems to fall within the purview of simplify to defeat these countermeasures.

Example Error: 
```
20:26:06.941 INFO  Main         - Options:
Input file: ./classes.dex
Output file: classes_simple.dex
Include filter: null
Exclude filter: null
Max execution time: 300
Max address visits: 10000
Max call depth: 50
Max method visits: 1000000
Max optimization passes: 100
Output API level: 15
Include support library: false


Error occurred while disassembling class Lcom.aalyatim.ssu.SSU; - skipping class
org.jf.util.ExceptionWithContext: The last instruction in the method is truncated
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:87)
        at org.jf.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(DexBackedMethodImplementation.java:75)
        at org.jf.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(VariableSizeLookaheadIterator.java:60)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:409)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:692)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:256)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:209)
        at org.jf.baksmali.Adaptors.MethodDefinition.<init>(MethodDefinition.java:92)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeVirtualMethods(ClassDefinition.java:325)
        at org.jf.baksmali.Adaptors.ClassDefinition.writeTo(ClassDefinition.java:112)
        at org.jf.baksmali.Baksmali.disassembleClass(Baksmali.java:152)
        at org.jf.baksmali.Baksmali.access$000(Baksmali.java:46)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:76)
        at org.jf.baksmali.Baksmali$1.call(Baksmali.java:74)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Error while processing method Lcom/aalyatim/ssu/SSU;->onCreate(Landroid/os/Bundle;)V
```

Dalvik executable that caused the error: https://mega.nz/#!xMkzHT4Z!2mSUf_8B4Tl3TUHbbBT2MXZFZCkm9UOiMDH55DojREU

**Comment by CalebFenton** [comment]
Disassembly is handled by dexlib, so it's not something I can fix. Please raise an issue here: https://github.com/JesusFreke/smali Before doing so, make sure the dex is valid and the app runs.

This looks like an error that has been fixed in an unreleased most recent version. If that's the case, it'll get fixed as soon as it's pushed to maven.

**Comment by RomanHargrave** [comment]
I'll try building simplify with that version.
