### ISSUE TITLE
Problem with running sample app

### ISSUE THREAD

**Issue by nguyenvulong** [CalebFenton/simplify#66]
I downloaded and built the project successfully but  when i tried to run the example, it did not work as expected. Please see the attached images below.
Any suggestion please,

Thank you!

```
Creating class manager with this path: /home/longnv/tools/simplify-master/simplify/obfuscated-example
Executing: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Exception in thread "main" java.lang.RuntimeException: Error loading class definition: Landroid/icu/text/MessagePatternUtil;
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:169)
	at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:188)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:121)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:140)
	at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:114)
	at org.cf.smalivm.dex.SmaliClassLoader.findClass(SmaliClassLoader.java:92)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:486)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	at org.cf.smalivm.context.ClonerFactory.build(ClonerFactory.java:57)
	at org.cf.smalivm.context.ExecutionContext.<init>(ExecutionContext.java:39)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:173)
	at org.cf.smalivm.VirtualMachine.spawnRootContext(VirtualMachine.java:164)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:62)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(java.base@9-internal/Reader.java:78)
	at java.io.InputStreamReader.<init>(java.base@9-internal/InputStreamReader.java:97)
	at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:166)
	... 15 more
```

![image](https://cloud.githubusercontent.com/assets/1311412/23064350/0a980e64-f553-11e6-90cf-3ddfcac53863.png)

![image](https://cloud.githubusercontent.com/assets/1311412/23064365/196e1d5c-f553-11e6-9650-d22dfc2cb6b4.png)

**Comment by CalebFenton** [comment]
Did you do a recursive clone?

**Comment by nguyenvulong** [comment]
The last time i download the zipped project, unpacked and ran it
This time I did try the recursive clone as described in the main page of this project. However I still encountered some exception below:

![image](https://cloud.githubusercontent.com/assets/1311412/23103237/45747fbe-f6fb-11e6-97b4-80c290c8bd3a.png)

Text format:

`Creating class manager with this path: /home/longnv/tools/simplify-master/simplify/simplify/obfuscated-example
Executing: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Simplifying: Lorg/cf/obfuscated/Reflection;->secretMethod2()V
Optimizations:
	constantized ifs = 0
	constantized ops = 0
	dead assignments removed = 0
	dead ops removed = 0
	dead results removed = 0
	nops removed = 0
	peephole optmizations = 0
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
Executing: Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V
23:26:50.616 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-static {r7, r13}, Lorg/cf/obfuscated/DESCrypt;->decrypt([BLjava/lang/String;)Ljava/lang/String;} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Can't find Smali file for Ljava/lang/reflect/InaccessibleObjectException;
23:26:50.622 WARN  NodeExecutor - ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-static {r3}, Lorg/cf/obfuscated/StringHolder;->get(I)Ljava/lang/String;} threw a real exception but was caught by an exception handler. This may be a bug in smalivm or in the input code. Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;-><clinit>()V, op=invoke-static {}, Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/StringHolder;->cacheStrings()Ljava/util/Map;, op=invoke-virtual {r5}, Ljava/lang/Throwable;->printStackTrace()V} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
Exception in thread "main" java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Lorg/cf/obfuscated/Reflection;->reflectSecretMethod2()V, op=invoke-virtual {r0}, Ljava/lang/Throwable;->printStackTrace()V} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:64)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:191)
	at org.cf.simplify.Launcher.run(Launcher.java:153)
	at org.cf.simplify.Main.main(Main.java:14)`

**Comment by CalebFenton** [comment]
It works for me. The error mentions "java.lang.reflect.inaccessibleobjectexception". Did you compile with Java 9?

**Comment by nguyenvulong** [comment]
Yes I am using OpenJDK 9
I'll try a fresh build again, debug it  and let you know by the end of this week. 
It could be some conflicts with my other tools
Thank you!

![image](https://cloud.githubusercontent.com/assets/1311412/23109266/e981d084-f75a-11e6-9f07-e28dd6884843.png)

**Comment by CalebFenton** [comment]
Try running it in Java 8. The error you posted before mentioned a class
which only existed in Java 9. I haven't tried it on there yet but I know it
might break some apps.

**Comment by nguyenvulong** [comment]
Thanks for the heads up!
I changed the java version to 1.8 (openjdk) and it returned the same result as java 8 did
![image](https://cloud.githubusercontent.com/assets/1311412/23121283/26b1becc-f7a3-11e6-9451-f4d622803114.png)


The analysis went through some warnings:

![image](https://cloud.githubusercontent.com/assets/1311412/23121050/3f980898-f7a2-11e6-9725-0326b0f84ddc.png)

and some exceptions like this

![image](https://cloud.githubusercontent.com/assets/1311412/23121030/28f172aa-f7a2-11e6-86db-5449bc1c6aa2.png)

but eventually it's successfully running
![image](https://cloud.githubusercontent.com/assets/1311412/23121009/0bb98ca4-f7a2-11e6-9c7c-cfd55b78da17.png)

**Comment by CalebFenton** [comment]
That output is normal, especially the warnings. The errors are 
https://guides.github.com/features/mastering-markdown/Generally, if an optimized dex is created, it means nothing went that bad. Dexlib handles the heavy lifting of building the dex and it's pretty strict.
