### ISSUE TITLE
[Garbage Collector overusage] when trying to simplify this obfuscated malware sample

### ISSUE THREAD

**Issue by Disane** [CalebFenton/simplify#82]
Hey Caleb,

Me and Tim are trying to crack a packer used for a malware. Unfortunately I ran into a problem that caused simplify to crash unexpectedly while trying to run it on a classes.dex file
Java version:

> java version "1.8.0_131"
> Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
> Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

command used: 
`java -jar simplify-1.1.0.jar -it 'com/nesrcnte' /mnt/hgfs/VMWareShared/.../Samples/com.hfpdyvdc.dpqtb-1/classes.dex`
Error log:
```
Executing: Lcom/nesrcnte/denetiw/iflkebriz;->odfxd(Ljava/lang/Object;ILjava/lang/Object;II)I
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.HashMap$KeySet.iterator(HashMap.java:916)
	at java.util.HashSet.iterator(HashSet.java:172)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:406)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerArrayList.clone(FastClonerArrayList.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneArray(Cloner.java:473)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:429)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.deepClone(Cloner.java:302)
	at org.cf.smalivm.context.Heap.cloneItem(Heap.java:187)
	at org.cf.smalivm.context.Heap.get(Heap.java:69)
	at org.cf.smalivm.context.Heap.get(Heap.java:89)
	at org.cf.smalivm.context.BaseState.peekRegister(BaseState.java:90)
```

I did some research on the error and it seems that the GC is having trouble recovering memory at each cycle. http://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html
Maybe I'm not letting the system use up enough memory for simplify to run, but other samples have worked great. Only this one is giving simplify trouble. Maybe I should limit the analysis even more, but that function that I'm trying to simplify would be interesting to deobfuscate. In the meantime I can try and go around it.

OS: Ubuntu 16.04, virtualized using VMware
Koodus Link to APK:  https://koodous.com/apks/ac2e627f1401659d87975e9e224c868d885129b49dc34c04ff01c90ac29788ef

Please take a look when you have time.

Btw. I really enjoy using your tools! 
They are really straight forward! 
Keep them coming! :)

**Comment by CalebFenton** [comment]
Could you share the hash?

There's an option to disable that warning, and you can bump up the heap size as a work around. :)

**Comment by Disane** [comment]
SHA1: e27f8e864dc85bb9fc4a089e9bc40849ad81998f
Grab the sample from Koodus! I linked it in the thread above!
https://koodous.com/apks/ac2e627f1401659d87975e9e224c868d885129b49dc34c04ff01c90ac29788ef/analysis

**Comment by CalebFenton** [comment]
I read the two issues you made right after waking up and missed those details. Thanks :D

**Comment by CalebFenton** [comment]
Closing for now. Let me know if the work-around doesn't work.
