### ISSUE TITLE
NullPointerException in ConstantBuilder.buildConstant

### ISSUE THREAD

**Issue by CalebFenton** [CalebFenton/simplify#85]
db3705df3cd1dc1b4e31e9b23729ec4c3674cf49 banker.dex

Execution seems to work, but there's an error during simplification.

```
(44 / 21) Executing top level method: Lcom/eivdcvl/bnlyawqvs/q5a19oAmv7xUV79ywpc;->YES3Fx9lh6WM6NchVnbRjB()J
Simplifying: Lcom/eivdcvl/bnlyawqvs/q5a19oAmv7xUV79ywpc;->YES3Fx9lh6WM6NchVnbRjB()J
Exception in thread "main" java.lang.NullPointerException
at org.cf.simplify.ConstantBuilder.buildConstant(ConstantBuilder.java:173)
at org.cf.simplify.ConstantBuilder.buildConstant(ConstantBuilder.java:197)
at org.cf.simplify.strategy.ConstantPropagationStrategy.perform(ConstantPropagationStrategy.java:53)
at org.cf.simplify.Optimizer.simplify(Optimizer.java:109)
at org.cf.simplify.Launcher.executeClass(Launcher.java:200)
at org.cf.simplify.Launcher.run(Launcher.java:151)
at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment]
This works now. I think it was fixed here https://github.com/CalebFenton/simplify/commit/c2ca436f3e6e88fdd88057cca7a605ecbcec43f1#diff-0ad209f060008e9d4210dd37cdc87934.
