### ISSUE TITLE
Smalivm is failing

### ISSUE THREAD

**Issue by voider1** [CalebFenton/simplify#91]
I was trying to run this on some APK's and I keep getting the error:

```
Exception in thread "main" java.lang.RuntimeException: Error loading class definition: Ljava/lang/Object;
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:168)
	at org.cf.smalivm.type.ClassManager.parseClassIfNecessary(ClassManager.java:187)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:120)
	at org.cf.smalivm.type.ClassManager.getVirtualType(ClassManager.java:139)
	at org.cf.smalivm.type.ClassManager.getVirtualClass(ClassManager.java:113)
	at org.cf.smalivm.type.VirtualClass.getImmediateAncestors(VirtualClass.java:60)
	at org.cf.smalivm.type.VirtualClass.getAncestors0(VirtualClass.java:46)
	at org.cf.smalivm.type.VirtualClass.getAncestors(VirtualClass.java:73)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:176)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:96)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:72)
	at TestKt.main(Test.kt:15)
Caused by: java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at org.cf.smalivm.dex.SmaliParser.parse(SmaliParser.java:69)
	at org.cf.smalivm.type.ClassManager.parseClass(ClassManager.java:165)
	... 12 more
```

**Comment by CalebFenton** [comment]
I run this on some APKs and I don't get this error.

Can you tell me which APKs you run this on and how you're running it?

**Comment by CalebFenton** [comment]
Looks like you're using smalivm as a library -- how'd you build the library? Does the jar contain framework Smali?

**Comment by voider1** [comment]
@CalebFenton Can I get smalivm on its own? I basically ripped it out, put the dependencies in the right place and tried to build it... Are there instructions on using smalivm on its own?

**Comment by CalebFenton** [comment]
Yes, you can get it on its own. If you build the project using `gradle fatjar`, it creates `smalivm/bulid/libs/smalivm-*.jar`. Here's how it looks on my machine:

```
caleb@haxcalibur  ~/repos/simplify/smalivm/build/libs ‹ruby-2.3.0› ‹master*›
╰─$ ls -alh
total 70M
drwxr-xr-x 3 caleb staff 102 Oct 13 13:28 .
drwxr-xr-x 6 caleb staff 204 Oct 13 13:28 ..
-rw-r--r-- 1 caleb staff 70M Oct 31 14:56 smalivm-1.2.0.jar
```

You'd then import `smalivm-1.2.0.jar` into your project and use it that way. If you want to rip it out for whatever reason (I would advise against it), you'll need to include everything from `smalivm/src/main/resources` yourself.
