### ISSUE TITLE
Uncompleted unreflection on an unpacked dex file

### ISSUE THREAD

**Issue by enovella** [CalebFenton/simplify#94]
Apparently, the unreflection is uncompleted as discussed over Twitter (https://twitter.com/enovella_/status/946847978261753856)

The method `findclass` should resolve the reflection method `getDeclaredMethod` and thus it should be something like: `this.c.loadClass(...)`

## Before simplify
![simplifybefore-jeb](https://user-images.githubusercontent.com/14809754/34448564-db5e4052-ecee-11e7-8340-ca582905e56f.png)

## After simplify
![simplifyafter-jeb](https://user-images.githubusercontent.com/14809754/34448566-e1a2f322-ecee-11e7-9129-f7ff1fb2f2da.png)

**DEX file**
[classencryptionDumped-dex.zip](https://github.com/CalebFenton/simplify/files/1593959/classencryptionDumped-dex.zip)

**Comment by enovella** [comment]
Should not simplify to remove the calls `QC$a.j(...)`? They have been decrypted and dumped in the original variables.

**Comment by enovella** [comment]
Another example that crashes.

**Sample:**
[dumped-1525772793579.zip](https://github.com/CalebFenton/simplify/files/1983329/dumped-1525772793579.zip)

**Output:**
```sh
$ java -jar simplify-1.2.0.jar /tmp/classes.dex [1 / 1] Processing top level class Lo/fe$ʹ;
(1 / 6) Executing top level method: Lo/fe$ʹ;->findClass(Ljava/lang/String;)Ljava/lang/Class;
11:55:14.524 WARN  MethodReflector - Failed to reflect Ljava/lang/Class;->getDeclaredMethod(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;: null
Simplifying: Lo/fe$ʹ;->findClass(Ljava/lang/String;)Ljava/lang/Class;
Optimizations:
	constantized ifs = 0
	constantized ops = 27
	dead assignments removed = 64
	dead ops removed = 8
	dead results removed = 6
	nops removed = 0
	peephole optmizations = 4
	unreflected fields = 0
	unreflected methods = 0
	useless gotos removed = 0
(2 / 6) Executing top level method: Lo/fe$ʹ;->ˎ()Ljava/lang/Object;
Simplifying: Lo/fe$ʹ;->ˎ()Ljava/lang/Object;
11:55:16.159 ERROR InvokeOp     - Unexpected real exception initializing Object
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:40)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:439)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:72)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException: null
	at javax.crypto.Cipher$Transform.<init>(Cipher.java:365)
	... 46 common frames omitted
11:55:16.187 ERROR InvokeOp     - Unexpected real exception initializing Object
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:40)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:439)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:72)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException: null
	at javax.crypto.Cipher$Transform.<init>(Cipher.java:365)
	... 46 common frames omitted
11:55:16.240 ERROR InvokeOp     - Unexpected real exception initializing Object
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:40)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:439)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:72)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException: null
	at javax.crypto.Cipher$Transform.<init>(Cipher.java:365)
	... 46 common frames omitted
11:55:16.276 ERROR InvokeOp     - Unexpected real exception initializing Object
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.cf.smalivm.ObjectInstantiator.newInstance(ObjectInstantiator.java:40)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalObjectInit(InvokeOp.java:439)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:72)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
Caused by: java.lang.NullPointerException: null
	at javax.crypto.Cipher$Transform.<init>(Cipher.java:365)
	... 46 common frames omitted
11:55:16.597 WARN  MethodReflector - Failed to reflect Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe;: No such accessible method: getUnsafe() on class: sun.misc.Unsafe
11:55:16.598 ERROR NodeExecutor - ExecutionNode{signature=Ljava/util/concurrent/ConcurrentHashMap;-><clinit>()V, op=invoke-static {}, Lsun/misc/Unsafe;->getUnsafe()Lsun/misc/Unsafe;, @=54} unhandled virtual exception: {}
java.lang.NoSuchMethodException: No such accessible method: getUnsafe() on class: sun.misc.Unsafe
	at org.apache.commons.beanutils.MethodUtils.invokeStaticMethod(MethodUtils.java:599)
	at org.cf.smalivm.MethodReflector.invoke(MethodReflector.java:118)
	at org.cf.smalivm.MethodReflector.reflect(MethodReflector.java:42)
	at org.cf.smalivm.opcode.InvokeOp.executeNonLocalMethod(InvokeOp.java:458)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:103)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:205)
	at org.cf.smalivm.context.ExecutionContext.readClassState(ExecutionContext.java:132)
	at org.cf.smalivm.opcode.NewInstanceOp.execute(NewInstanceOp.java:37)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.context.ExecutionContext.staticallyInitializeClassIfNecessary(ExecutionContext.java:205)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:96)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:77)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
11:55:16.600 WARN  ExecutionContext - Unhandled virtual exception: java.lang.NoSuchMethodException: No such accessible method: getUnsafe() on class: sun.misc.Unsafe
11:55:16.601 ERROR UnreflectionStrategy - Unable to unreflect method invocation @88
java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Ljavax/crypto/Cipher;->getInstance(Ljava/lang/String;)Ljavax/crypto/Cipher;, op=invoke-static {r1, r0}, Ljavax/crypto/Cipher;->createCipher(Ljava/lang/String;Ljava/security/Provider;)Ljavax/crypto/Cipher;, @=1} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Ljavax/crypto/Cipher;->createCipher(Ljava/lang/String;Ljava/security/Provider;)Ljavax/crypto/Cipher;, op=invoke-static {r3, r7, r2}, Ljavax/crypto/Cipher;->tryCombinations(Ljavax/crypto/Cipher$InitParams;Ljava/security/Provider;[Ljava/lang/String;)Ljavax/crypto/Cipher$CipherSpiAndProvider;, @=7} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Ljavax/crypto/Cipher;->tryCombinations(Ljavax/crypto/Cipher$InitParams;Ljava/security/Provider;[Ljava/lang/String;)Ljavax/crypto/Cipher$CipherSpiAndProvider;, op=invoke-static {}, Ljava/security/Security;->getProviders()[Ljava/security/Provider;, @=213} and was not handled. This could be a bug in smalivm.
Exception: java.lang.RuntimeException: Real exception was thrown executing ExecutionNode{signature=Ljava/security/Security;-><clinit>()V, op=new-instance r6, Ljava/util/concurrent/ConcurrentHashMap;, @=43} and was not handled. This could be a bug in smalivm.
Exception: java.lang.NullPointerException
	at org.cf.smalivm.NodeExecutor.execute(NodeExecutor.java:88)
	at org.cf.smalivm.MethodExecutor.execute(MethodExecutor.java:62)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:103)
	at org.cf.smalivm.VirtualMachine.execute(VirtualMachine.java:82)
	at org.cf.smalivm.opcode.InvokeOp.executeLocalMethod(InvokeOp.java:355)
	at org.cf.smalivm.opcode.InvokeOp.execute(InvokeOp.java:140)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:52)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.replaceInstruction(ExecutionGraphManipulator.java:226)
	at org.cf.simplify.strategy.UnreflectionStrategy.replaceMethodInvoke(UnreflectionStrategy.java:524)
	at org.cf.simplify.strategy.UnreflectionStrategy.perform(UnreflectionStrategy.java:136)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:112)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at org.cf.util.Utils.getIntegerValue(Utils.java:167)
	at org.cf.smalivm.context.HeapItem.asInteger(HeapItem.java:50)
	at org.cf.smalivm.opcode.AGetOp.execute(AGetOp.java:71)
	at org.cf.smalivm.context.ExecutionNode.execute(ExecutionNode.java:50)
	at org.cf.simplify.ExecutionGraphManipulator.recreateAndExecute(ExecutionGraphManipulator.java:367)
	at org.cf.simplify.ExecutionGraphManipulator.rebuildGraph(ExecutionGraphManipulator.java:396)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:196)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstruction(ExecutionGraphManipulator.java:200)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.cf.simplify.ExecutionGraphManipulator.removeInstructions(ExecutionGraphManipulator.java:208)
	at org.cf.simplify.strategy.DeadRemovalStrategy.perform(DeadRemovalStrategy.java:200)
	at org.cf.simplify.Optimizer.simplify(Optimizer.java:109)
	at org.cf.simplify.Launcher.executeClass(Launcher.java:210)
	at org.cf.simplify.Launcher.run(Launcher.java:149)
	at org.cf.simplify.Main.main(Main.java:14)
```

**Comment by CalebFenton** [comment]
The problem is the invocation arguments aren't known. In this case with:

```java
DexFile.class.getDeclaredMethod("loadClass", new Class[] { String.class, ClassLoader.class }).invoke(this.c, new Object[] { paramString, this });
```

The `paramString` is unknown, and this leads to the `Object[]` parameter becoming unknown. This was a problem because `UnreflectionStrategy.buildMethodInvokeReplacement` assumed it needed a _known_ parameters value (the `Object[]` bit). But all the code used it for was to get the length of the array. However, this can actually just be deduced from the number of parameters of the method.

After the fix, you get something like this:

```java
Object[] arrayOfObject = new Object[2];
arrayOfObject[0] = paramString;
arrayOfObject[1] = this;
paramString = ((DexFile)localObject).loadClass((String)arrayOfObject[0], (ClassLoader)arrayOfObject[1]);
```

This is better, but it's still not perfect.  What's needed now is a new constant propagation strategy that detects these obvious array references. I think dead code strategy will clean it up nicely afterwards.
